// Keeps the generated images in their own marked block, so the rest of a
// profile README is never touched. If the markers look damaged we refuse to
// guess and leave the file alone.

export const START = "<!-- customize-you-profile:start -->";
export const END = "<!-- customize-you-profile:end -->";
export const NOTE = "<!-- Generated by CustomizeYouProfile: this block is rewritten on every run. Move the whole block anywhere you like, or set `update-readme: false` to place the images yourself. -->";

export class ReadmeMarkerError extends Error {}

const count = (s, needle) => s.split(needle).length - 1;

export function updateReadme(current, block, position = "top") {
  const section = `${START}\n${NOTE}\n${block}\n${END}`;
  if (current === null || current.trim() === "") return `${section}\n`;
  const starts = count(current, START), ends = count(current, END);
  if (starts === 0 && ends === 0)
    return position === "bottom"
      ? `${current.replace(/\s*$/, "")}\n\n${section}\n`
      : `${section}\n\n${current}`;
  const s = current.indexOf(START), e = current.indexOf(END);
  if (starts !== 1 || ends !== 1 || e < s)
    throw new ReadmeMarkerError(
      `found ${starts} start and ${ends} end marker(s) in the README, so it was left untouched. ` +
      `Keep exactly one "${START}" … "${END}" pair (or delete both to start over).`);
  return current.slice(0, s) + section + current.slice(e + END.length);
}
